/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientedda;

import Entidades.Evento;
import Entidades.Mensaje;
import Entidades.Partida;
import Entidades.Usuario;
import Remotas.IFachadaServidor;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Nan
 */
public class FrmLogin extends javax.swing.JFrame implements IFrmAppCliente {

    private static IFachadaServidor fachada;
    private static ITableroUI tablero;

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin(IFachadaServidor fachada) {
        initComponents();
        this.fachada = fachada;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtNombre = new javax.swing.JTextField();
        TxtContrasena = new javax.swing.JTextField();
        BtnIngresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(3);

        BtnIngresar.setText("Ingresar");

        jLabel1.setText("Nombre");

        jLabel2.setText("Contraseña");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(161, 161, 161))
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(BtnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(BtnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrmLogin(fachada).setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIngresar;
    private javax.swing.JTextField TxtContrasena;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void Procesar(Mensaje msg) {
        if (msg.getEvento() == Evento.CREAR_NUEVA_PARTIDA) {
//            lstClientes.setListData(((ArrayList<Cliente>) msg.getMensaje()).toArray());
            Usuario u = (Usuario) msg.getAux();
            FrmPreJuego frm = new FrmPreJuego(u,fachada);
            
            frm.setVisible(true);
            this.setVisible(false);
            try {
                ControladorPrePartida cpp = new ControladorPrePartida(fachada, frm);
            } catch (RemoteException ex) {
                Logger.getLogger(FrmLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (msg.getEvento() == Evento.INGRESO_A_PARTIDA) {
            Partida p = (Partida) msg.getAux();
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog (null, "La apuesta inicial es de $" + (p.getPozo()/2) + ", Desea unirse?","Warning",dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION){
              
                        FrmTablero frm = new FrmTablero((Partida) p);
                        frm.setTitle("Usuario: " + p.getJugadorDos().getNombreUsu() + "  Saldo Actual: " + p.getJugadorDos().getSaldo());
                        frm.setVisible(true);
                        this.setVisible(false);
                        try {
                            ControladorPartida cp = new ControladorPartida(frm,fachada, (Partida) p);
                        } catch (RemoteException ex) {
                            Logger.getLogger(FrmLogin.class.getName()).log(Level.SEVERE, null, ex);
                        }
            }
            
        }else if(msg.getEvento() == Evento.ADMINISTRADOR){
//            Usuario p = (Partida) msg.getAux();
            Usuario adm = (Usuario) msg.getAux();
            FrmAdministrador frm = new FrmAdministrador(fachada);
            frm.setTitle("Aministrador: " + adm.getNombreCompleto() );
            try {
                ControladorAdministrador ca = new ControladorAdministrador(fachada, frm);
            } catch (RemoteException ex) {
                Logger.getLogger(FrmPreJuego.class.getName()).log(Level.SEVERE, null, ex);
            }
            frm.setVisible(true);
        
        }else if (msg.getEvento() == Evento.PARTIDA_CREADA) {
//            LstPartidas.setListData(((ArrayList<Partida>) msg.getAux()).toArray());
            
            Partida p = (Partida) msg.getAux();
            FrmTablero frm = new FrmTablero(p);
            frm.setTitle("Usuario: " + p.getJugadorUno().getNombreUsu() + "  Saldo Actual: " + p.getJugadorUno().getSaldo());
            try {
                ControladorPartida cp = new ControladorPartida(frm, fachada, p);
            } catch (RemoteException ex) {
                Logger.getLogger(FrmPreJuego.class.getName()).log(Level.SEVERE, null, ex);
            }
            frm.setVisible(true);

        }else if (msg.getEvento() == Evento.SALDO_INSUFICIENTE){
            JOptionPane.showMessageDialog(null, "No tiene saldo suficiente para jugar");
        }else if (msg.getEvento() == Evento.USUARIO_YA_LOGUEADO){
            JOptionPane.showMessageDialog(null, "Este usuario ya esta logueado");
     }
    }

    @Override
    public void setController(Controlador controlador) {
        this.BtnIngresar.addActionListener(controlador);
    }

    @Override
    public String obtenerNombreIngresado() {
        return TxtNombre.getText();
    }

    @Override
    public String obtenerContrasenaIngresada() {
        return TxtContrasena.getText();
    }

    private void mostrarMensaje(String msg) {
        JOptionPane.showConfirmDialog(null, msg);
    }

}
